Ticket3939 interpolation accuracy
ISISComputingGroup/EPICS-KeithleyDVM pull request #4
Opened 2019-03-12 15:13 UTC by LiamPanchaud

Includes spline interpolation developer defined function plus googletests to ensure correct working.

2019-03-28 13:02 UTC, Alistair-McGann-Tessella requested changes

2019-03-28 13:02 UTC, Alistair-McGann-Tessella commented on Keithley_2700Sup/user1DTableSub.c
> +    if (isInit) {
How expensive is the fitting process, and how often will the spline need to be evaluated? If it is quick and cheap, or isn't evaluated very often, I would consider dropping the Init flag and have it always fit the spline

2019-03-28 13:02 UTC, Alistair-McGann-Tessella commented on Keithley_2700Sup/user1DTableSub.c
> +        gsl_spline_init(spline, x_data, y_data, len_arr);
The GSL documentation example shows these quantities getting freed after their use: 
https://www.gnu.org/software/gsl/doc/html/interp.html#d-interpolation-example-programs

Is this getting performed? If not, could this be a memory leak?

2019-03-28 13:02 UTC, Alistair-McGann-Tessella commented on run_tests.bat
> +exit /B %keithley_2700_tests_failed%
Needs a newline

2019-03-28 13:02 UTC, Alistair-McGann-Tessella commented on Keithley_2700Sup/drift_utils.cpp
> +}
Needs a newline

2019-03-28 13:02 UTC, Alistair-McGann-Tessella commented on Keithley_2700Sup/drift_utils.cpp
> +        new_drift = temp_change_over_time + previous_drift;
This looks different to the algorithm on the wiki

2019-03-28 13:02 UTC, Alistair-McGann-Tessella commented on Keithley_2700Sup/drift_utils.cpp
> +        printf("Assigned new drift with nans to %f\n", new_drift);
How often will this write to the IOC console? Is this a required statement for logging?

2019-03-28 13:02 UTC, Alistair-McGann-Tessella commented on Keithley_2700Sup/parse_buffer_readings.c
> +	unsigned long i = 0;
I recently got feedback that use of unsigned types is discouraged by the Google C++ style guidelines. I don't see the use here is a problem, but I am curious as to why you made this change.

2019-04-04 11:31 UTC, FreddieAkeroyd commented on Keithley_2700Sup/user1DTableSub.c
> +    if (isInit) {
You mean drop the Init flag from the implementation but not the interface?

2019-04-11 14:12 UTC, LiamPanchaud commented on Keithley_2700Sup/parse_buffer_readings.c
> +	unsigned long i = 0;
I _think_ it was to mitigate a compiler warning where something unsighed was being compared to `i` (which was signed at the time). Some field in the record (I suspect it was `noa`) uses an unsigned value, and I thought it best to match the types

2019-04-11 14:59 UTC, LiamPanchaud commented on Keithley_2700Sup/drift_utils.cpp
> +        printf("Assigned new drift with nans to %f\n", new_drift);
Removed

2019-04-11 15:25 UTC, LiamPanchaud commented on Keithley_2700Sup/user1DTableSub.c
> +    if (isInit) {
It's _reasonably_ expensive, and although I have no doubt that the computer could handle doing this, it doesn't seem like it's worth making it do all the extra work of fitting every few seconds

2019-04-11 15:44 UTC, LiamPanchaud commented on Keithley_2700Sup/user1DTableSub.c
> +        gsl_spline_init(spline, x_data, y_data, len_arr);
This is now noted in the [convert record wiki page](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Convert-Record#tips-tricks-and-gotchas) in point 3

2019-05-01 17:15 UTC, Alistair-McGann-Tessella approved these changes

2019-05-01 17:23 UTC, merged